import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  Box,
  Container,
  VStack,
  Center,
  Flex,
  Button,
  Text,
} from "@chakra-ui/react";
export default function Home() {
  return (
    <Box>
      <Head>
        <title>Property Handle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        position="relative"
        backgroundImage="url('/bg.png')"
        backgroundPosition="bottom bottom"
        backgroundRepeat="no-repeat"
        height="100vh"
        width="100vw"
        style={{ backgroundSize: "cover" }}
      >
        <Box
          position="absolute"
          top="0"
          bottom="0"
          left="0"
          right="0"
          bg="#A926B1"
          opacity="0.4"
        ></Box>
        <Container maxW="container.xl">
          <Flex align="center" justify="space-between" py="1.2rem">
            <Box></Box>
            <Box zIndex="100">
              <Flex align="center" gap="2.5rem" ml="auto">
                <Link href="/" passHref>
                  <a
                    style={{
                      color: "#fff",
                      fontSize: "1.4rem",
                      lineHeight: "41.18px",
                    }}
                  >
                    Home
                  </a>
                </Link>
                <Link href="/" passHref>
                  <a
                    style={{
                      color: "#fff",
                      fontSize: "1.4rem",
                      lineHeight: "41.18px",
                    }}
                  >
                    Properties
                  </a>
                </Link>
                <Link href="/" passHref>
                  <a
                    style={{
                      color: "#fff",
                      fontSize: "1.4rem",
                      lineHeight: "41.18px",
                    }}
                  >
                    Contact Us
                  </a>
                </Link>
                <Link href="/" passHref>
                  <a
                    style={{
                      color: "#fff",
                      fontSize: "1.4rem",
                      lineHeight: "41.18px",
                    }}
                  >
                    User
                  </a>
                </Link>
              </Flex>
            </Box>
          </Flex>
          <Center height="80vh">
            <VStack>
              <Image alt="logo" width="350" height="300" src="/logo.svg" />
              {/* <Text
                color="#fcfcfc"
                py="1rem"
                fontSize="1.5rem"
                fontStyle="italic"
              >
                Democratizing access to real estate
              </Text> */}

              <Flex gap={{base: '2rem', md: '5rem'}} pt={{ base: '1rem', md: '5rem' }} direction={{base: 'column', md: 'row'}}>
                <Link href="/dashboard/investor" passHref>
                  <Button
                    variant="solid"
                    bg="purple"
                    color="white"
                    width="252px"
                    height="50px"
                  >
                    Investor Dashboard
                  </Button>
                </Link>
                <Link href="/dashboard/issuer" passHref>
                  <Button
                    variant="solid"
                    bg="purple"
                    color="white"
                    width="252px"
                    height="50px"
                  >
                    Issuer Dashboard
                  </Button>
                </Link>
                <Link href="/dashboard" passHref>
                  <Button
                    variant="solid"
                    bg="purple"
                    color="white"
                    width="252px"
                    height="50px"
                  >
                    Admin Dashboard
                  </Button>
                </Link>
              </Flex>
            </VStack>
          </Center>
        </Container>
      </Box>
    </Box>
  );
}
/* Vector */


